# Generated by Django 5.1.5 on 2025-02-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="special_request",
            field=models.TextField(blank=True, null=True),
        ),
    ]
