# Generated by Django 5.1.5 on 2025-02-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_mealcategory_dish"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealcategory",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
