# Generated by Django 5.1.5 on 2025-02-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_mealcategory_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealcategory",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="dishes_photos/"),
        ),
    ]
