# Generated by Django 5.1.5 on 2025-02-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_remove_mealcategory_img_mealcategory_ico_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=13)),
                ("subject", models.CharField(max_length=256)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.DateField(auto_now=True)),
            ],
        ),
    ]
